# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'CustomTabCenterBig' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomTabCenterBig
pod "ESTabBarController-swift"

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'

end



